# Generated by Django 3.1.7 on 2021-04-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='payment_id',
            field=models.CharField(max_length=200),
        ),
    ]
