# Generated by Django 3.1.7 on 2021-04-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='settled_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='settled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
