# Generated by Django 3.1.7 on 2021-04-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210404_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardInformation',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credit_card_params', serialize=False, to='payments.payment')),
                ('amount', models.IntegerField()),
                ('method', models.CharField(choices=[('credit_card', 'credit_card'), ('mbway', 'mbway')], max_length=50)),
                ('number', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=19)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MbwayInformation',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mbway_params', serialize=False, to='payments.payment')),
                ('amount', models.IntegerField()),
                ('method', models.CharField(choices=[('credit_card', 'credit_card'), ('mbway', 'mbway')], max_length=50)),
                ('phone_number', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='CreditCardAdditionalParams',
        ),
        migrations.DeleteModel(
            name='MbwayAdditionalParams',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='additional_params',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('error', 'error'), ('settled', 'settled')], default='success', max_length=20),
        ),
    ]
